"""Add Rejected status to maintenance_requests enum

Revision ID: b41d3e098e9d
Revises: d291c7bfd5a1
Create Date: 2025-05-09 20:44:27.665887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b41d3e098e9d'
down_revision = 'd291c7bfd5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('Pending', 'In Progress', 'Resolved', 'Cancelled'),
               type_=sa.Enum('Pending', 'In Progress', 'Resolved', 'Cancelled', 'Rejected', name='request_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'In Progress', 'Resolved', 'Cancelled', 'Rejected', name='request_status'),
               type_=mysql.ENUM('Pending', 'In Progress', 'Resolved', 'Cancelled'),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'"))
    # ### end Alembic commands ###