"""Add scheduled_date to maintenance_requests

Revision ID: d291c7bfd5a1
Revises: 498a1604032c
Create Date: 2025-04-22 20:54:59.570045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd291c7bfd5a1'
down_revision = '498a1604032c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_table('contracts')
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('video',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('map_location',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('apartments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('Owner', 'Administrator', 'Buyer/Tenant', 'Technician'),
               type_=sa.Enum('Administrator', 'Buyer/Tenant', 'Owner', 'Technician'),
               existing_nullable=False)
        batch_op.alter_column('job',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('facebook_link',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('job',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('Administrator', 'Buyer/Tenant', 'Owner', 'Technician'),
               type_=mysql.ENUM('Owner', 'Administrator', 'Buyer/Tenant', 'Technician'),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('apartments_ibfk_1', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('map_location',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('video',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=mysql.BIGINT(),
               nullable=True)

    op.create_table('contracts',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('contract_details', mysql.TEXT(), nullable=False),
    sa.Column('signed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='contracts_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('due_date', mysql.TIMESTAMP(), nullable=False),
    sa.Column('paid_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('status', mysql.ENUM('Pending', 'Completed', 'Overdue'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='payments_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transactions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', mysql.ENUM('Rent', 'Sale', 'Maintenance'), nullable=False),
    sa.Column('status', mysql.ENUM('Pending', 'Completed', 'Overdue'), nullable=False),
    sa.Column('payment_method', mysql.ENUM('Visa', 'MasterCard', 'Cash'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transactions_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
